name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
        ls -al
    - name: checkin

      run: |
        python hello.py


  YoudaoNote-checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-python
        uses: actions/setup-python@master
        with:
          python-version: 3.7

      - name: checkin
        run: |
          python3 hello.py